openapi: 3.0.0
info:
  version: 1.0.0
  title: PeerRequest API
  description: PeerRequest Open API Specification.
paths: null
components:
  parameters:
    category_id:
      name: category_id
      in: path
      required: true
      description: The id of the category to retrieve
      schema:
        type: string
    entry_id:
      name: entry_id
      in: path
      required: true
      description: The id of the entry to retrieve
      schema:
        type: string
    limit:
      name: limit
      in: query
      description: How many items to return at one time
      required: false
      schema:
        min: 1
        max: 100
        default: 100
        type: integer
        format: int32
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  responses:
    UnexpectedError:
      description: unexpected error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
