openapi: "3.0.0"
info:
  version: 1.0.0
  title: PeerRequest API
  description: PeerRequest Open API Specification.
  #servers:
  # TODO: add servers here
paths:
  # auth endpoints
  /auth/logout:
    $ref: "./paths/auth/logout.yaml"

  /auth/login:
    $ref: "./paths/auth/login.yaml"

  /auth/callback:
    $ref: "./paths/auth/callback.yaml"

  # category endpoints
  /categories:
    $ref: "./paths/categories.yaml"

  /categories/{category_id}:
    $ref: "./paths/categories/category_id/category.yaml"

  # entry endpoints
  /categories/{category_id}/entries:
    $ref: "./paths/categories/category_id/entries.yaml"

  /categories/{category_id}/entries/{entry_id}:
    $ref: "./paths/categories/category_id/entries/entry_id/entry.yaml"

  /categories/{category_id}/entries/{entry_id}/paper:
    $ref: "./paths/categories/category_id/entries/entry_id/paper.yaml"

  # review endpoints
  /reviews:
    $ref: "./paths/reviews.yaml"

  /categories/{category_id}/entries/{entry_id}/reviews:
    $ref: "./paths/categories/category_id/entries/entry_id/reviews.yaml"

  /categories/{category_id}/entries/{entry_id}/reviews/{review_id}:
    $ref: "./paths/categories/category_id/entries/entry_id/reviews/review_id/review.yaml"

  /categories/{category_id}/entries/{entry_id}/reviews/{review_id}/document:
    $ref: "./paths/categories/category_id/entries/entry_id/reviews/review_id/document.yaml"

  # user endpoints
  /users/{user_id}/entries:
    $ref: "./paths/users/user_id/entries.yaml"

  /users/{user_id}:
    $ref: "./paths/users/user_id/user.yaml"

  /users/self:
    $ref: "./paths/users/self.yaml"

  /users/self/entries:
    $ref: "./paths/users/self/entries.yaml"

components:
  parameters:
    $ref: "./parameters/_index.yaml"
  schemas:
    $ref: "./schemas/_index.yaml"
  responses:
    $ref: "./responses/_index.yaml"