openapi: "3.0.0"
info:
  version: 1.0.0
  title: PeerRequest API
  description: PeerRequest Open API Specification.
  #servers:
  # TODO: add servers here
paths:
# TODO: add paths here

components:
  parameters:
    $ref: "./parameters/_index.yaml"
  schemas:
    $ref: "./schemas/_index.yaml"
  responses:
    $ref: "./responses/_index.yaml"