openapi: "3.0.0"
info:
  version: 1.0.0
  title: PeerRequest API
  description: PeerRequest Open API Specification.
  #servers:
  # TODO: add servers here
paths:
  # /auth endpoints
  /auth/logout:
    $ref: "./paths/auth/logout.yaml"

  /auth/login:
    $ref: "./paths/auth/login.yaml"

  /auth/callback:
    $ref: "./paths/auth/callback.yaml"

  # TODO: add paths here

  # user endpoints
  /{user_id}/entries:
    $ref: "./parameters/paths/user/entries.yaml"

  /{user_id}/entries/{entry_id}:
    $ref: "./parameters/paths/user/entry.yaml"

  /{user_id}/reviews:
    $ref: "./parameters/paths/user/reviews.yaml"

  /{user_id}/reviews/{review_id}:
    $ref: "./parameters/paths/user/review.yaml"

  /users/{user_id}:
     $ref: "./parameters/paths/user/account.yaml"


components:
  parameters:
    $ref: "./parameters/_index.yaml"
  schemas:
    $ref: "./schemas/_index.yaml"
  responses:
    $ref: "./responses/_index.yaml"