openapi: "3.0.0"
info:
  version: 1.0.0
  title: PeerRequest API
  description: PeerRequest Open API Specification.
  #servers:
  # TODO: add servers here

tags:
  - name: categories
  - name: entries
  - name: direct_requests
  - name: reviews
  - name: messages
  - name: users

paths:
  # category endpoints
  /categories:
    $ref: "./paths/categories.yaml"

  /categories/{category_id}:
    $ref: "./paths/categories/category_id/category.yaml"

  # entry endpoints
  /entries:
    $ref: "./paths/entries.yaml"

  /categories/{category_id}/entries:
    $ref: "./paths/categories/category_id/entries.yaml"

  /categories/{category_id}/entries/{entry_id}:
    $ref: "./paths/categories/category_id/entries/entry_id/entry.yaml"

  /categories/{category_id}/entries/{entry_id}/paper:
    $ref: "./paths/categories/category_id/entries/entry_id/paper.yaml"

  # direct request controller
  /requests:
    $ref: "./paths/requests.yaml"

  /categories/{category_id}/entries/{entry_id}/process:
    $ref: "./paths/categories/category_id/entries/entry_id/process.yaml"

  /categories/{category_id}/entries/{entry_id}/process/requests:
    $ref: "./paths/categories/category_id/entries/entry_id/process/requests.yaml"

  /categories/{category_id}/entries/{entry_id}/process/claim:
    $ref: "./paths/categories/category_id/entries/entry_id/process/claim.yaml"

  /categories/{category_id}/entries/{entry_id}/process/requests/{request_id}:
    $ref: "./paths/categories/category_id/entries/entry_id/process/requests/request_id/request.yaml"

  # review endpoints
  /reviews:
    $ref: "./paths/reviews.yaml"

  /categories/{category_id}/entries/{entry_id}/reviews:
    $ref: "./paths/categories/category_id/entries/entry_id/reviews.yaml"

  /categories/{category_id}/entries/{entry_id}/reviews/{review_id}:
    $ref: "./paths/categories/category_id/entries/entry_id/reviews/review_id/review.yaml"

  /categories/{category_id}/entries/{entry_id}/reviews/{review_id}/document:
    $ref: "./paths/categories/category_id/entries/entry_id/reviews/review_id/document.yaml"
  
  # message endpoints
  /categories/{category_id}/entries/{entry_id}/reviews/{review_id}/messages:
    $ref: "./paths/categories/category_id/entries/entry_id/reviews/review_id/messages.yaml"

  /categories/{category_id}/entries/{entry_id}/reviews/{review_id}/messages/{message_id}:
    $ref: "./paths/categories/category_id/entries/entry_id/reviews/review_id/messages/message_id/message.yaml"

  # user endpoints

components:
  parameters:
    $ref: "./parameters/_index.yaml"
  schemas:
    $ref: "./schemas/_index.yaml"
  responses:
    $ref: "./responses/_index.yaml"