openapi: "3.0.0"
info:
  version: 1.0.0
  title: PeerRequest API
  description: PeerRequest Open API Specification.
  #servers:
  # TODO: add servers here

tags:
  - name: auth
  - name: categories
  - name: entries
  - name: reviews
  - name: users

paths:
  # auth endpoints
  /api/logout:
    $ref: "./paths/auth/logout.yaml"

    # category endpoints
  /api/categories:
    $ref: "./paths/categories.yaml"

  /api/categories/{category_id}:
    $ref: "./paths/categories/category_id/category.yaml"

    # entry endpoints
  /api/categories/{category_id}/entries:
    $ref: "./paths/categories/category_id/entries.yaml"

  /api/categories/{category_id}/entries/{entry_id}:
    $ref: "./paths/categories/category_id/entries/entry_id/entry.yaml"

  /api/categories/{category_id}/entries/{entry_id}/paper:
    $ref: "./paths/categories/category_id/entries/entry_id/paper.yaml"

    # review endpoints
  /api/reviews:
    $ref: "./paths/reviews.yaml"

  /api/categories/{category_id}/entries/{entry_id}/reviews:
    $ref: "./paths/categories/category_id/entries/entry_id/reviews.yaml"

  /api/categories/{category_id}/entries/{entry_id}/reviews/{review_id}:
    $ref: "./paths/categories/category_id/entries/entry_id/reviews/review_id/review.yaml"

  /api/categories/{category_id}/entries/{entry_id}/reviews/{review_id}/document:
    $ref: "./paths/categories/category_id/entries/entry_id/reviews/review_id/document.yaml"

    # user endpoints
  /api/users/{user_id}/entries:
    $ref: "./paths/users/user_id/entries.yaml"

  /api/users/{user_id}:
    $ref: "./paths/users/user_id/user.yaml"

  /api/users/self:
    $ref: "./paths/users/self.yaml"

  /api/users/self/entries:
    $ref: "./paths/users/self/entries.yaml"

components:
  parameters:
    $ref: "./parameters/_index.yaml"
  schemas:
    $ref: "./schemas/_index.yaml"
  responses:
    $ref: "./responses/_index.yaml"