openapi: "3.0.0"
info:
  version: 1.0.0
  title: PeerRequest API
  description: PeerRequest Open API Specification.
  #servers:
  # TODO: add servers here
paths:
  # /auth endpoints
  /auth/logout:
    $ref: "./paths/auth/logout.yaml"

  /auth/login:
    $ref: "./paths/auth/login.yaml"

  /auth/callback:
    $ref: "./paths/auth/callback.yaml"

  # /categories endpoints
  /categories/{category_id}/entries:
    $ref: "./paths/categories/category_id/entries.yaml"

  /categories/{category_id}/entries/{entry_id}:
    $ref: "./paths/categories/category_id/entry.yaml"

  /categories/{category_id}/entries/{entry_id}/paper:
    $ref: "./paths/categories/category_id/entry_id/paper.yaml"

  #review endpoints
  /reviews:
    $ref: "./paths/reviews.yaml"

  /reviews/{review_id}:
    $ref: "./paths/reviews/review_id/review.yaml"

  /reviews/{review_id}/{messageBoardComment_id}:
    $ref: "./paths/reviews/review_id/messageBoardComment.yaml"

  # TODO: add paths here

components:
  parameters:
    $ref: "./parameters/_index.yaml"
  schemas:
    $ref: "./schemas/_index.yaml"
  responses:
    $ref: "./responses/_index.yaml"